# Generated by Django 6.0.3 on 2026-03-17 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_datetime', models.DateTimeField()),
                ('chief_complaint', models.TextField(blank=True)),
                ('labor_start_time', models.DateTimeField(blank=True, null=True)),
                ('full_dilation_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True)),
                ('delivery_type', models.CharField(blank=True, choices=[('nsd', 'Normal Spontaneous Delivery'), ('assisted', 'Assisted Delivery'), ('cs', 'Cesarean Section'), ('referral', 'Referral')], max_length=20)),
                ('presentation', models.CharField(blank=True, choices=[('cephalic', 'Cephalic'), ('breech', 'Breech'), ('transverse', 'Transverse'), ('other', 'Other')], max_length=20)),
                ('placenta_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_blood_loss', models.DecimalField(blank=True, decimal_places=0, help_text='mL', max_digits=6, null=True)),
                ('complications', models.TextField(blank=True)),
                ('maternal_condition', models.TextField(blank=True)),
                ('referral_hospital', models.CharField(blank=True, max_length=200)),
                ('referral_reason', models.TextField(blank=True)),
                ('discharge_datetime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_doctor', to=settings.AUTH_USER_MODEL)),
                ('attending_midwife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_midwife', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='patients.patient')),
            ],
            options={
                'ordering': ['-admission_datetime'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryComplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complication_type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_taken', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complication_records', to='delivery.deliveryrecord')),
            ],
        ),
        migrations.CreateModel(
            name='LaborMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('contraction_frequency', models.CharField(blank=True, help_text='e.g. 3 in 10 min', max_length=100)),
                ('contraction_duration', models.CharField(blank=True, help_text='seconds', max_length=100)),
                ('fetal_heart_rate', models.PositiveIntegerField(blank=True, help_text='bpm', null=True)),
                ('cervical_dilation', models.DecimalField(blank=True, decimal_places=1, help_text='cm', max_digits=3, null=True)),
                ('maternal_bp_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('maternal_bp_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('maternal_pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('membrane_status', models.CharField(choices=[('intact', 'Intact'), ('ruptured', 'Ruptured'), ('artificial', 'Artificially Ruptured')], default='intact', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('delivery_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_monitoring', to='delivery.deliveryrecord')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
