# Generated by Django 6.0.3 on 2026-03-18 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('patients', '0002_maternalimmunization'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilHealthClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(blank=True, max_length=50)),
                ('case_rate_type', models.CharField(choices=[('nsd', 'NSD — Normal Spontaneous Delivery (₱6,500)'), ('cs', 'CS — Cesarean Section (₱19,000)'), ('premature', 'Premature Delivery (₱8,000)'), ('ectopic', 'Ectopic Pregnancy (₱10,000)'), ('abortion', 'Abortion/Miscarriage (₱4,000)'), ('newborn_care', 'Newborn Care Package (₱1,750)'), ('prenatal', 'Prenatal Package Z (₱2,500)'), ('other', 'Other / Custom')], max_length=30)),
                ('case_rate_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('member_pin', models.CharField(blank=True, max_length=20, verbose_name='PhilHealth PIN')),
                ('date_of_service', models.DateField()),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('amount_reimbursed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Submission'), ('submitted', 'Submitted to PhilHealth'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmit', 'For Resubmission'), ('paid', 'Paid by PhilHealth')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='philhealth_claims', to='billing.bill')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='philhealth_claims', to='patients.patient')),
            ],
        ),
    ]
