# Generated by Django 6.0.3 on 2026-03-18 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('patients', '0002_maternalimmunization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostpartumVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('24hr', '24-hour check (Day 1)'), ('3day', '3-day check'), ('7day', '1-week check (Day 7)'), ('6week', '6-week postpartum'), ('other', 'Other / Follow-up')], default='6week', max_length=10)),
                ('days_postpartum', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('uterine_involution', models.CharField(blank=True, help_text='e.g. Well-involuted, at umbilicus, not palpable', max_length=200)),
                ('lochia', models.CharField(blank=True, help_text='Color, amount, odor — rubra/serosa/alba', max_length=200)),
                ('wound_status', models.CharField(blank=True, help_text='Episiotomy/CS wound condition', max_length=200)),
                ('breast_condition', models.CharField(blank=True, help_text='Engorgement, cracking, mastitis signs', max_length=200)),
                ('breastfeeding', models.CharField(choices=[('exclusive', 'Exclusive Breastfeeding'), ('mixed', 'Mixed (BF + formula)'), ('formula', 'Formula only'), ('none', 'Not breastfeeding')], default='exclusive', max_length=20)),
                ('perineum_status', models.CharField(blank=True, max_length=200)),
                ('mood_score', models.IntegerField(blank=True, help_text='EPDS total score (0-30). ≥10 = possible depression', null=True)),
                ('mood_notes', models.TextField(blank=True, help_text='Notes on emotional/mental health status')),
                ('fp_counseled', models.BooleanField(default=False)),
                ('fp_method_chosen', models.CharField(choices=[('none', 'No method yet'), ('lam', 'LAM (Lactational Amenorrhea)'), ('pills', 'Combined Oral Pills'), ('minipill', 'Progestin-only Pill'), ('injectable', 'Injectable (DMPA)'), ('condom', 'Condom'), ('iud', 'IUD / IUS'), ('implant', 'Implant'), ('btl', 'BTL / Bilateral Tubal Ligation'), ('nfp', 'NFP / Natural Family Planning'), ('other', 'Other')], default='none', max_length=20)),
                ('fp_method_provided', models.BooleanField(default=False)),
                ('newborn_weight', models.IntegerField(blank=True, help_text='grams', null=True)),
                ('newborn_condition', models.CharField(blank=True, max_length=200)),
                ('newborn_feeding', models.CharField(blank=True, max_length=200)),
                ('chief_complaint', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('prescribed_medicines', models.TextField(blank=True)),
                ('referral', models.CharField(blank=True, max_length=200)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attending_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postpartum_visits', to='delivery.deliveryrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postpartum_visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
