# Generated by Django 6.0.3 on 2026-03-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewbornRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.CharField(blank=True, max_length=200)),
                ('baby_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('indeterminate', 'Indeterminate')], max_length=15)),
                ('birth_datetime', models.DateTimeField()),
                ('weight_grams', models.DecimalField(decimal_places=0, help_text='grams', max_digits=6)),
                ('length_cm', models.DecimalField(decimal_places=1, help_text='cm', max_digits=4)),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('chest_circumference_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('apgar_1min', models.PositiveIntegerField(blank=True, null=True)),
                ('apgar_5min', models.PositiveIntegerField(blank=True, null=True)),
                ('birth_status', models.CharField(choices=[('alive', 'Alive'), ('stillbirth', 'Stillbirth'), ('neonatal_death', 'Neonatal Death')], default='alive', max_length=20)),
                ('initial_diagnosis', models.TextField(blank=True)),
                ('vitamin_k_given', models.BooleanField(default=False)),
                ('eye_prophylaxis_given', models.BooleanField(default=False)),
                ('newborn_screening_done', models.BooleanField(default=False)),
                ('newborn_screening_date', models.DateField(blank=True, null=True)),
                ('discharge_datetime', models.DateTimeField(blank=True, null=True)),
                ('discharge_weight_grams', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newborns', to='delivery.deliveryrecord')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newborns', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='NewbornImmunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('date_given', models.DateField()),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('administered_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('newborn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='newborn.newbornrecord')),
            ],
        ),
    ]
