# Generated by Django 6.0.3 on 2026-03-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='BirthCare Clinic', max_length=200)),
                ('clinic_tagline', models.CharField(blank=True, default='Maternity & Newborn Care Services', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('philhealth_accno', models.CharField(blank=True, max_length=50, verbose_name='PhilHealth Accreditation No.')),
                ('doh_license', models.CharField(blank=True, max_length=50, verbose_name='DOH License No.')),
                ('head_physician', models.CharField(blank=True, max_length=200)),
                ('head_midwife', models.CharField(blank=True, max_length=200)),
                ('default_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_room_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('logo_url', models.CharField(blank=True, default='🌸', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic Settings',
            },
        ),
    ]
