# Generated by Django 6.0.3 on 2026-03-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('live_in', 'Live-in')], default='single', max_length=20)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('partner_name', models.CharField(blank=True, max_length=200)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('existing_conditions', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('high', 'High Risk'), ('moderate', 'Moderate Risk')], default='low', max_length=10)),
                ('gravida', models.PositiveIntegerField(default=0, help_text='Total pregnancies')),
                ('para', models.PositiveIntegerField(default=0, help_text='Total deliveries')),
                ('abortion_history', models.PositiveIntegerField(default=0)),
                ('lmp', models.DateField(blank=True, null=True, verbose_name='Last Menstrual Period')),
                ('edd', models.DateField(blank=True, null=True, verbose_name='Expected Date of Delivery')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('delivery_type', models.CharField(blank=True, max_length=100)),
                ('outcome', models.CharField(choices=[('live_birth', 'Live Birth'), ('stillbirth', 'Stillbirth'), ('abortion', 'Abortion'), ('ectopic', 'Ectopic')], max_length=20)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('complications', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_history', to='patients.patient')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
