# Generated by Django 6.0.3 on 2026-03-18 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternalImmunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(choices=[('tt1', 'Tetanus Toxoid 1 (TT1)'), ('tt2', 'Tetanus Toxoid 2 (TT2)'), ('tt3', 'Tetanus Toxoid 3 (TT3)'), ('tt4', 'Tetanus Toxoid 4 (TT4)'), ('tt5', 'Tetanus Toxoid 5 (TT5)'), ('flu', 'Influenza'), ('hepb', 'Hepatitis B'), ('covid', 'COVID-19'), ('other', 'Other')], max_length=20)),
                ('date_given', models.DateField()),
                ('given_by', models.CharField(blank=True, max_length=200)),
                ('facility', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maternal_immunizations', to='patients.patient')),
            ],
            options={
                'ordering': ['-date_given'],
            },
        ),
    ]
