# Generated by Django 6.0.3 on 2026-03-17 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenatalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('gestational_age_weeks', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='kg', max_digits=5)),
                ('blood_pressure_systolic', models.PositiveIntegerField()),
                ('blood_pressure_diastolic', models.PositiveIntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, help_text='°C', max_digits=4)),
                ('fetal_heart_rate', models.PositiveIntegerField(blank=True, help_text='bpm', null=True)),
                ('fundal_height', models.DecimalField(blank=True, decimal_places=1, help_text='cm', max_digits=4, null=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('assessment', models.TextField()),
                ('plan', models.TextField()),
                ('prescribed_medicines', models.TextField(blank=True)),
                ('lab_request', models.TextField(blank=True)),
                ('ultrasound_request', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('risk_flag', models.CharField(choices=[('normal', 'Normal'), ('borderline', 'Borderline'), ('high_risk', 'High Risk')], default='normal', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attending_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('result', models.TextField(blank=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('notes', models.TextField(blank=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='prenatal.prenatalvisit')),
            ],
        ),
        migrations.CreateModel(
            name='UltrasoundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('findings', models.TextField()),
                ('ga_by_ultrasound', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('image_file', models.FileField(blank=True, null=True, upload_to='ultrasounds/')),
                ('done_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasounds', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prenatal.prenatalvisit')),
            ],
        ),
    ]
